uploads = []

[[generated]]
id = "ukPrXpaI1hzvGvUpD9CGF"
uri = "file://artifacts/solarworks/assets/images/icon.png"
type = "image"
title = "solarworks icon"

[[outputs]]
id = "IPBRqIfP4u-tloLMdKzyj"
uri = "file://artifacts/solarworks/assets/solarworks_price_list.csv"
type = "table"
title = "SolarWorks Price List CSV"
